import json
import urllib.parse
import re
import time
from bs4 import BeautifulSoup
from playwright.sync_api import sync_playwright
from mcp.server.fastmcp import FastMCP

# Initialize the MCP Server
mcp = FastMCP("VolaFlightAssistant")

def parse_flight_stage(stage_element):
    """Helper to parse takeoff and landing details."""
    if not stage_element:
        return None
    
    stage_data = {}
    header_div = stage_element.select_one('div.justify-space-between')
    raw_header = header_div.get_text(separator=" ", strip=True) if header_div else ""
    stage_data['date'] = raw_header.split('•')[0].strip() if '•' in raw_header else raw_header
    
    locations = stage_element.select('div.stage-timeline-location')
    if len(locations) >= 2:
        # Takeoff
        t_time = locations[0].select_one('div.stage-timeline-location__first-line')
        t_time_match = re.search(r'\d{2}:\d{2}', t_time.get_text(separator=" ", strip=True) if t_time else "")
        stage_data['takeoff_time'] = t_time_match.group() if t_time_match else "N/A"
        
        # Landing (using -1 to skip layovers if they exist in the UI)
        l_time = locations[-1].select_one('div.stage-timeline-location__first-line')
        l_time_match = re.search(r'\d{2}:\d{2}', l_time.get_text(separator=" ", strip=True) if l_time else "")
        stage_data['landing_time'] = l_time_match.group() if l_time_match else "N/A"

    return stage_data

@mcp.tool()
def search_vola_flights(origin_iata: str, destination_iata: str, min_days: int = 3, max_days: int = 7) -> str:
    """
    Searches Vola.ro for flight options and prices.
    
    Args:
        origin_iata: The 3-letter IATA code for the departure city (e.g., 'BUH' for Bucharest).
        destination_iata: The 3-letter IATA code for the arrival city (e.g., 'ROM' for Rome).
        min_days: Minimum stay duration in days (default 3).
        max_days: Maximum stay duration in days (default 7).
        
    Returns:
        A JSON string containing a list of available flights with dates, times, and prices.
    """
    # 1. Autogenerate the URL
    base_url = "https://www.vola.ro/search_results"
    query_params = {
        "from": f"CITY:{origin_iata.upper()}",
        "to": f"CITY:{destination_iata.upper()}",
        "flex": "1",
        "funit": "any",
        "fdmin": min_days,
        "fdmax": max_days,
        "ad": 1,
        "cc": "ECONOMY"
    }
    url = f"{base_url}?{urllib.parse.urlencode(query_params)}"
    
    scraped_flights = []

    # 2. Scrape the autogenerated URL
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page()
        
        try:
            page.goto(url, wait_until="networkidle")
            page.wait_for_selector('div.flight-card__details', timeout=20000)
            time.sleep(2) 

            soup = BeautifulSoup(page.content(), 'html.parser')
            flight_cards = soup.select('div.flight-card__details')

            for details_div in flight_cards:
                flight_data = {}
                card = details_div.parent
                
                stages = card.select('li.stage')
                flight_data['outbound'] = parse_flight_stage(stages[0]) if len(stages) > 0 else None
                flight_data['inbound'] = parse_flight_stage(stages[1]) if len(stages) > 1 else None

                # Extract Price
                actions_elem = card.select_one('div.flight-card__actions')
                raw_actions_text = actions_elem.get_text(separator=" ", strip=True) if actions_elem else ""
                price_match = re.search(r'(?:Preț:|Price:)\s*(\d+\s*€)', raw_actions_text)
                flight_data['price'] = price_match.group(1) if price_match else "N/A"

                scraped_flights.append(flight_data)

        except Exception as e:
            return json.dumps({"error": f"Failed to scrape flights: {str(e)}"})
        finally:
            browser.close()

    # 3. Return the data to the AI model as JSON
    return json.dumps(scraped_flights)

if __name__ == "__main__":
    mcp.run()