name: Deploy Workflow
on:
  push:
    branches:
      - main
      - dev
      - test
  pull_request:
    branches:
      - main
      - dev
      - test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v6
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements_files/requirements.txt
      - name: Perform linting with pylint
        id: pylint-test
        run: |
          pylint src/ --disable=R0903,C0303,W0718,R1732,R0914,R0801
          pylint main.py --disable=R0903,C0303,W0718,R1732,R0914,R0801
      - name: Perform linting with flake8
        run: | 
          flake8 src/
          flake8 main.py
